/**
 * The analyst's review log, sources, risk register and methodology notes.
 *
 * GENERATED by scripts/asts/extract-provenance.py from reference/asts/finalize.py
 * (evaluated with the stamped analytics.json, as finalize.py does). Do not edit:
 * this is the analyst's text, and the page must show it as written.
 */
export interface ReviewItem { id: string; raised: string; finding: string; evidence: string; resolution: string; status: string }
export const REVIEW_LOG: readonly ReviewItem[] = [
  {
    "id": "R-01",
    "raised": "A2",
    "finding": "Regression beta is statistically weak; A3 separately argued ~10.5% Ke is too low for a pre-commercial firm.",
    "evidence": "Raw beta 1.42, SE 0.60 (95% CI 0.24-2.60), R2 5%; yr1 1.04 vs yr2 2.17. CAPM prices only systematic risk.",
    "resolution": "Blume-adjusted beta (1.28), live from IBKR data. Failure risk handled via explicit Distress/Bear scenarios, not a hand-inflated rate (avoids double count). WACC+/-2pp shown live.",
    "status": "Resolved"
  },
  {
    "id": "R-02",
    "raised": "A2",
    "finding": "Final weekly bar is a partial week.",
    "evidence": "Bar dated 8-Sep-2026 closes mid-week.",
    "resolution": "Excluded from regression and vol; retained as current price.",
    "status": "Resolved"
  },
  {
    "id": "R-03",
    "raised": "A2",
    "finding": "Should Bear/Distress carry higher WACCs?",
    "evidence": "Scenario dispersion is cash-flow risk; CAPM rate should not vary by scenario.",
    "resolution": "Single WACC path for all scenarios.",
    "status": "Resolved"
  },
  {
    "id": "R-04",
    "raised": "A3",
    "finding": "$1,724mm of satellite CIP is already paid: ignoring it double-counts capex; full credit may overstate.",
    "evidence": "CIP also holds NRE, early-unit overruns and later launch deposits (10-Q Note 4).",
    "resolution": "Base credits 50% (MC 25-75%). Tornado: +/- ~$1/sh - second-order.",
    "status": "Resolved"
  },
  {
    "id": "R-05",
    "raised": "A3",
    "finding": "Up-C: Class B/C shares represent exchangeable AST LLC units.",
    "evidence": "Using Class A only (299.8mm) would overstate $/sh by ~30%.",
    "resolution": "S0 = A+B+C = 389.2mm; check ties to 10-Q cover.",
    "status": "Resolved"
  },
  {
    "id": "R-06",
    "raised": "A3",
    "finding": "SBC ($63.5mm/qtr) must not be added back.",
    "evidence": "SBC is a real transfer to employees.",
    "resolution": "SBC deducted in EBITDA/FCFF; existing unvested RSUs also counted in shares (small overlap - conservative).",
    "status": "Resolved"
  },
  {
    "id": "R-07",
    "raised": "A3",
    "finding": "Convert dilution depends on value per share -> circularity risk.",
    "evidence": "Excel circular refs are fragile and order-dependent if sorted.",
    "resolution": "Proved: prefix converts iff value-with-prefix > its K; SUMIF formulation is order-independent, no circular refs. Verified in 12 break tests.",
    "status": "Resolved"
  },
  {
    "id": "R-08",
    "raised": "A3",
    "finding": "Restricted cash $428.4mm is collateral for $420mm UBS bridge.",
    "evidence": "10-Q Note 3.",
    "resolution": "Both included so they net; excluded from 'available liquidity' in Risk.",
    "status": "Resolved"
  },
  {
    "id": "R-09",
    "raised": "A1",
    "finding": "2034 notes carry a capped call ($79.57 -> $149.20).",
    "evidence": "Pricing 8-K Jul-2026.",
    "resolution": "Trigger = cap, D = n x cap. Capped-call time value and 2.375% capped call ignored (conservative).",
    "status": "Documented"
  },
  {
    "id": "R-10",
    "raised": "A3",
    "finding": "Contract liabilities ($266.9mm) are revenue already received in cash.",
    "evidence": "10-Q revenue note.",
    "resolution": "Deducted as non-cash revenue unwind over 2027-31.",
    "status": "Resolved"
  },
  {
    "id": "R-11",
    "raised": "A1",
    "finding": "Ligado spectrum commitments missing from naive models.",
    "evidence": "10-K: $550mm at closing, >= $80mm/yr, revenue share.",
    "resolution": "Included; revenue-share % not disclosed (3% placeholder, flagged).",
    "status": "Open (data)"
  },
  {
    "id": "A3-01",
    "raised": "A3",
    "finding": "Explicit revenue declined 2036-40 while TV assumed +2.5%.",
    "evidence": "ARPU erosion applied forever; adoption saturated.",
    "resolution": "Repricing limited to 2027-32; long-run ARPU +1.5%, partner base +1%. Live CAGR-vs-g check added.",
    "status": "Fixed"
  },
  {
    "id": "A3-02",
    "raised": "A3",
    "finding": "Base EBITDA margin 61-65% exceeded Iridium 56.8%.",
    "evidence": "Network costs did not scale with fleet.",
    "resolution": "Added $2mm/sat/yr network opex. Remaining 64% accepted (pure wholesale model); 40-75% bound check.",
    "status": "Fixed"
  },
  {
    "id": "A2-01",
    "raised": "A2",
    "finding": "Bear EV turned negative; DCF forces uneconomic reinvestment.",
    "evidence": "No abandonment option in a fixed-plan DCF.",
    "resolution": "Equity floored at 0 (limited liability); Distress/Bear values are conservative lower bounds.",
    "status": "Documented"
  },
  {
    "id": "A2-02",
    "raised": "A2",
    "finding": "Iridium benchmark is survivorship-biased.",
    "evidence": "Original Iridium, Globalstar, ORBCOMM all went bankrupt.",
    "resolution": "40% combined probability on Distress+Bear (both ~$0-1/sh).",
    "status": "Resolved"
  },
  {
    "id": "A2-03",
    "raised": "A2",
    "finding": "Terminal year sits on a lumpy replacement wave.",
    "evidence": "Replacements cluster 2033-35, 2040.",
    "resolution": "TV uses normalised replacement capex = fleet / life / (1-loss) x unit cost.",
    "status": "Resolved"
  },
  {
    "id": "A2-04",
    "raised": "A2",
    "finding": "Revenue must respect network capacity.",
    "evidence": "Block 2: ~2,000 cells/sat.",
    "resolution": "Users-per-satellite plausibility check (<= 2.5mm); Base peak ~1.6mm.",
    "status": "Resolved"
  },
  {
    "id": "A3-03",
    "raised": "A3",
    "finding": "Capex timed at launch, not when paid.",
    "evidence": "Test: paying one period earlier = -426 $mm PV.",
    "resolution": "Base $57.40 -> $56.35 (-1.8%). Documented, not modelled.",
    "status": "Documented"
  },
  {
    "id": "A3-04",
    "raised": "A3",
    "finding": "Checks passed on first run - are they capable of failing?",
    "evidence": "Untested tests prove nothing.",
    "resolution": "12 break-tests (stress.py): every intended check fired; workbook = engine to 1e-14 in all cases.",
    "status": "Resolved"
  },
  {
    "id": "A3-05",
    "raised": "A3",
    "finding": "Sensitivity g-axis hard-coded; grid silently de-centred when g changed.",
    "evidence": "Surfaced by g = 6% break test.",
    "resolution": "Axis now = live g +/- offsets; centre check holds.",
    "status": "Fixed"
  },
  {
    "id": "A2-05",
    "raised": "A2",
    "finding": "Triangulate scenario weighting vs simulation.",
    "evidence": "MC mean $55.23 vs prob-weighted $52.88.",
    "resolution": "Agreement within 5%; both reported.",
    "status": "Resolved"
  },
  {
    "id": "A2-06",
    "raised": "A2",
    "finding": "MC robustness.",
    "evidence": "Correlation matrix PSD (min eig 0.24); SE of mean $0.41; running mean converged.",
    "resolution": "20,000 paths, fixed seed - reproducible.",
    "status": "Resolved"
  },
  {
    "id": "A3-06",
    "raised": "A3",
    "finding": "Stale equity-award counts.",
    "evidence": "AST LLC options (Jun-2025) and 2024-Plan RSUs (Dec-2025) are latest found.",
    "resolution": "Flagged in Capital_Structure. Each +1mm shares ~ -0.25% per share.",
    "status": "Open (data)"
  },
  {
    "id": "A3-07",
    "raised": "A3",
    "finding": "Possible Tax Receivable Agreement (common in Up-C).",
    "evidence": "Not confirmed in sources reviewed.",
    "resolution": "Not modelled; would reduce value if present. Confirm in 10-K.",
    "status": "Open (data)"
  },
  {
    "id": "A3-08",
    "raised": "A3",
    "finding": "Look-ahead / anchoring bias.",
    "evidence": "All inputs dated <= 10-Sep-2026.",
    "resolution": "No parameter calibrated to price; reverse DCF reported separately.",
    "status": "Pass"
  },
  {
    "id": "A2-07",
    "raised": "A2",
    "finding": "Overfitting.",
    "evidence": "Only beta estimated from history; shown with SE.",
    "resolution": "No curve-fitting of forecasts.",
    "status": "Pass"
  },
  {
    "id": "A3-09",
    "raised": "A3",
    "finding": "Currency consistency.",
    "evidence": "All figures USD (NASDAQ, SEC filings); holder reports in CAD.",
    "resolution": "Model in USD; convert at spot for portfolio use.",
    "status": "Documented"
  },
  {
    "id": "A3-10",
    "raised": "A3",
    "finding": "Liquidity test ignores committed financing for the Ligado payment.",
    "evidence": "10-K: $550mm non-recourse delayed-draw SPV commitment.",
    "resolution": "Noted on Risk sheet (Base headroom -$78mm -> ~+$472mm with facility). Valuation unaffected (FCFF).",
    "status": "Documented"
  },
  {
    "id": "A3-11",
    "raised": "A3",
    "finding": "Probability-weighting EV mixes in negative Distress EV (-$12bn).",
    "evidence": "Violates limited liability; averages a non-claim.",
    "resolution": "Only floored per-share values are weighted; weighted EV/equity removed from summary and dashboard.",
    "status": "Fixed"
  },
  {
    "id": "A1-01",
    "raised": "A1",
    "finding": "100% bonus depreciation (OBBBA 2025) drives cash taxes.",
    "evidence": "Tested bonus OFF in break tests.",
    "resolution": "Prob-weighted value moves < 1%; keep ON, verify with tax adviser.",
    "status": "Documented"
  }
];

export const SOURCES: ReadonlyArray<{ label: string; ref: string }> = [
  {
    "label": "Q2-2026 Form 10-Q (balance sheet, debt note, shares, PP&E)",
    "ref": "https://www.sec.gov/Archives/edgar/data/1780312/000119312526342550/asts-20260630.htm"
  },
  {
    "label": "Q2-2026 business update deck (8-K ex. 99.2)",
    "ref": "https://www.sec.gov/Archives/edgar/data/0001780312/000119312526342540/asts-ex99_2.htm"
  },
  {
    "label": "2034 1.625% notes pricing (8-K ex. 99.1, Jul-2026)",
    "ref": "https://www.sec.gov/Archives/edgar/data/0001780312/000149315226033912/ex99-1.htm"
  },
  {
    "label": "2034 notes closing / net proceeds",
    "ref": "https://www.businesswire.com/news/home/20260721294685/en/"
  },
  {
    "label": "2036 2.25% notes pricing (8-K, Feb-2026)",
    "ref": "https://www.sec.gov/Archives/edgar/data/1780312/000149315226007126/ex99-1.htm"
  },
  {
    "label": "2036 2.00% notes conversion price",
    "ref": "https://app.dealroom.co/news/feed/ast-spacemobile-prices-1b-convertible-notes-offering-up-from-850m"
  },
  {
    "label": "2032 4.25% notes terms (8-K, Jan-2025)",
    "ref": "https://www.sec.gov/Archives/edgar/data/1780312/000149315225003793/ex99-1.htm"
  },
  {
    "label": "FY2025 Form 10-K (Ligado commitments, launch commitments)",
    "ref": "https://www.sec.gov/Archives/edgar/data/1780312/000178031226000006/asts-20251231.htm"
  },
  {
    "label": "Q1-2026 Form 10-Q (2020 Plan options)",
    "ref": "https://www.sec.gov/Archives/edgar/data/0001780312/000119312526216950/asts-20260331.htm"
  },
  {
    "label": "Q2-2026 earnings call ($21-23mm/sat, 45-60 sats, guidance)",
    "ref": "https://www.fool.com/earnings/call-transcripts/2026/08/17/ast-spacemobile-asts-q2-2026-earnings-call-transcript/"
  },
  {
    "label": "BlueBird Block 2 lifetime (secondary)",
    "ref": "https://space.skyrocket.de/doc_sdat/bluebird-2.htm"
  },
  {
    "label": "Interactive Brokers API - weekly OHLCV ASTS (conid 480745767), SPY (756733)",
    "ref": "Retrieved via connected IBKR account, 10-Sep-2026"
  },
  {
    "label": "10-year Treasury yield 4.84% (10-Sep-2026)",
    "ref": "https://tradingeconomics.com/united-states/government-bond-yield"
  },
  {
    "label": "Damodaran implied ERP 4.42% (1-Jul-2026)",
    "ref": "https://aswathdamodaran.blogspot.com/2026/07/country-risk-drivers-measures-and.html"
  },
  {
    "label": "Iridium FY2025 results (margin benchmark)",
    "ref": "https://investor.iridium.com/2026-02-12-Iridium-Announces-2025-Results-Issues-2026-Outlook"
  },
  {
    "label": "T-Mobile T-Satellite pricing ($10/mo)",
    "ref": "https://www.t-mobile.com/coverage/satellite-phone-service"
  }
];

export const RISK_REGISTER: ReadonlyArray<{ risk: string; levers: string; evidence: string }> = [
  {
    "risk": "Deployment slip / launch failure",
    "levers": "fl_*, loss_rate, MC delay",
    "evidence": "BB7 lost Apr-2026; history of Block 2 slips."
  },
  {
    "risk": "Adoption below plan (Starlink D2C competition)",
    "levers": "take_t1/t2, px_g",
    "evidence": "T-Satellite $10/mo, 650+ Starlink sats; #1 value driver."
  },
  {
    "risk": "Spectrum / regulatory (Ligado FCC approval)",
    "levers": "ligado_year, spec_fee",
    "evidence": "Application 'Pending Review' since Jan-2026."
  },
  {
    "risk": "Capital intensity / funding at depressed prices",
    "levers": "Funding gap rows above",
    "evidence": "Dilution below value is value-destructive; not in FCFF."
  },
  {
    "risk": "Satellite life shorter than 7 yrs",
    "levers": "sat_life",
    "evidence": "Secondary source only; drives replacement capex."
  },
  {
    "risk": "SBC-driven dilution",
    "levers": "sbc_* rows",
    "evidence": "Q2-26 SBC $63.5mm/qtr; treated as cost."
  },
  {
    "risk": "Key-person / governance (Up-C, Class C control)",
    "levers": "Not modelled",
    "evidence": "Founder controls via Class C voting shares."
  }
];

export const NOTES: ReadonlyArray<{ title: string; lines: string[] }> = [
  {
    "title": "HOW TO USE",
    "lines": [
      "Edit blue cells on Inputs only (scenario columns D-G; globals in D). Everything else recalculates. Confirm Checks!C3 reads ALL PASS.",
      "Monte Carlo, tornado, 2-D grids and reverse DCF are stamped values from analytics.py; re-run after changing inputs."
    ]
  },
  {
    "title": "METHOD",
    "lines": [
      "Unlevered DCF (FCFF) from 1-Jul-2026, valued at 10-Sep-2026, mid-period discounting with a period-specific WACC (growth phase fading 2031-35 to mature).",
      "Revenue: MNO wholesale revenue share = partner base x coverage(fleet) x logistic adoption x ASTS ARPU; plus government and gateway revenue.",
      "Constellation: fleet targets drive launches, cohort retirements after design life, launch losses, and CIP pre-funding credit.",
      "Tax: NOL pool with 80% cap; 100% bonus depreciation (switchable). Terminal: Gordon growth on normalised 2041 FCFF (steady-state replacement capex).",
      "Equity: EV + liquid assets - debt - converts at face, then an order-independent, value-consistent dilution engine converts instruments whose trigger < value.",
      "Four scenarios are all live; value is probability-weighted. Per-share values are floored at zero (limited liability)."
    ]
  },
  {
    "title": "KEY LIMITATIONS (see Review_Log for full list)",
    "lines": [
      "1. Forward drivers (adoption, ARPU, opex) are judgement - no one has observed mature D2D broadband economics. Tier-1 take rate dominates value.",
      "2. Fixed-plan DCF ignores management flexibility (abandonment/scale-back) - Distress/Bear values understate true option value of equity.",
      "3. Capital raises assumed at fair value; raising below intrinsic value would dilute further (see Risk funding gap).",
      "4. Ligado revenue-share %, possible Tax Receivable Agreement, and two stale award counts are unverified (Open items).",
      "5. Capex timed at launch (~-1.8% per-share impact if paid a year earlier). Block 1 satellites ignored for coverage (conservative).",
      "6. USD throughout. Not investment advice: this is an analytical model, and the author is not a financial adviser."
    ]
  }
];

export const CORRELATION_RATIONALE: ReadonlyArray<{ a: string; b: string; why: string }> = [
  {
    "a": "take_t1",
    "b": "take_t2",
    "why": "Common demand factor for D2D."
  },
  {
    "a": "take_t1",
    "b": "arpu_t1",
    "why": "Price elasticity: cheaper plans lift take-up."
  },
  {
    "a": "take_t2",
    "b": "arpu_t2",
    "why": "Price elasticity."
  },
  {
    "a": "unit_cost",
    "b": "delay",
    "why": "Programme stress raises cost and slips schedule together."
  },
  {
    "a": "delay",
    "b": "take_t1",
    "why": "Late network cedes share to Starlink D2C."
  }
];
