"""
Regenerates src/components/valuation/provenance.generated.ts from the analyst's
finalize.py — the review log, sources, risk register, simulation rationale and
methodology notes — verbatim.

The lists are pulled out of finalize.py's syntax tree and evaluated with the
stamped analytics.json bound as `A`, exactly as finalize.py itself does when it
writes the workbook, so the review log's interpolated evidence ("MC mean $55.23
vs prob-weighted $52.88") is the analyst's text, not a paraphrase of it.

    python3 scripts/asts/extract-provenance.py
"""
import ast, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
REF = os.path.join(ROOT, 'reference', 'asts')
src = open(os.path.join(REF, 'finalize.py')).read()
A = json.load(open(os.path.join(REF, 'analytics.json')))
ns = {'A': A, 'ct': A['capex_timing']}
want = {'LOG', 'SRC', 'NOTES', 'reg', 'rat'}
got = {}
for node in ast.walk(ast.parse(src)):
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        name = node.targets[0].id
        if name in want:
            got[name] = eval(compile(ast.Expression(node.value), 'finalize.py', 'eval'), ns)
assert set(got) == want, f'missing: {want - set(got)}'
log = [dict(zip(['id', 'raised', 'finding', 'evidence', 'resolution', 'status'], r)) for r in got['LOG']]
sources = [{'label': a, 'ref': b} for a, b in got['SRC']]
register = [{'risk': a, 'levers': b, 'evidence': c} for a, b, c in got['reg']]
notes, section = [], None
for t in got['NOTES']:
    if not t:
        continue
    # A header is upper-case up to any parenthetical: 'KEY LIMITATIONS (see Review_Log for full list)'.
    if t.split('(')[0].strip().isupper():
        section = {'title': t, 'lines': []}; notes.append(section)
    else:
        section['lines'].append(t)
rationale = [{'a': a, 'b': b, 'why': w} for (a, b), w in got['rat'].items()]
out = f'''/**
 * The analyst's review log, sources, risk register and methodology notes.
 *
 * GENERATED by scripts/asts/extract-provenance.py from reference/asts/finalize.py
 * (evaluated with the stamped analytics.json, as finalize.py does). Do not edit:
 * this is the analyst's text, and the page must show it as written.
 */
export interface ReviewItem {{ id: string; raised: string; finding: string; evidence: string; resolution: string; status: string }}
export const REVIEW_LOG: readonly ReviewItem[] = {json.dumps(log, indent=2, ensure_ascii=False)};

export const SOURCES: ReadonlyArray<{{ label: string; ref: string }}> = {json.dumps(sources, indent=2, ensure_ascii=False)};

export const RISK_REGISTER: ReadonlyArray<{{ risk: string; levers: string; evidence: string }}> = {json.dumps(register, indent=2, ensure_ascii=False)};

export const NOTES: ReadonlyArray<{{ title: string; lines: string[] }}> = {json.dumps(notes, indent=2, ensure_ascii=False)};

export const CORRELATION_RATIONALE: ReadonlyArray<{{ a: string; b: string; why: string }}> = {json.dumps(rationale, indent=2, ensure_ascii=False)};
'''
# Beside the components that render it, not in src/lib: these are citations the page
# links to, not vendors the code calls, and src/lib is where the licence guard
# (tests/routes.test.ts) rightly treats a hostname as a data dependency.
path = os.path.join(ROOT, 'src', 'components', 'valuation', 'provenance.generated.ts')
open(path, 'w').write(out)
print(f'wrote {path}: {len(log)} review items, {len(sources)} sources, {len(register)} risks, {len(notes)} note sections')
