'use client';

import * as React from 'react';
import {
  Area,
  AreaChart,
  CartesianGrid,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { AlertCircle, Calculator, LineChart, Plus, X } from 'lucide-react';
import { PageBody, PageHeader } from '@/components/layout/app-shell';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { InfoTip } from '@/components/ui/tooltip';
import { Stat } from '@/components/ui/stat';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  NumCell,
  NumHead,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { AXIS_PROPS, ChartFrame, ChartTooltip, GRID_PROPS } from '@/components/charts/chart-chrome';
import { useRouter } from 'next/navigation';
import { formatCurrency, formatPercent } from '@/lib/format';
import { planToBacktestConfig } from '@/lib/plan-bridge';
import { useWorkspace } from '@/store/workspace';
import { WrapperPanel } from '@/components/results/wrapper-panel';
import { cn } from '@/lib/utils';

/**
 * The planning workspace.
 *
 * A posted tax bracket is not what the next dollar costs. Once income-tested
 * benefits start withdrawing, the effective rate can be double the bracket, and
 * that gap appears nowhere on a tax return. This surfaces it, then answers the
 * question it raises: given that, where should this year's savings go?
 *
 * Powered by the CanPath engine (`lib/canpath`), whose figures all come from a
 * single provenance-tracked data file and whose port is verified against 235
 * fixtures generated by an independent Python reference.
 */

const ACCOUNT_LABELS: Record<string, string> = {
  employer_match: 'Employer match',
  fhsa: 'FHSA',
  resp: 'RESP',
  rrsp: 'RRSP',
  tfsa: 'TFSA',
  non_registered: 'Non-registered',
};

const ACCOUNT_WHY: Record<string, string> = {
  employer_match: 'Free money, and it uses the same RRSP room your own contributions do.',
  fhsa: 'The only account that is deductible going in and tax-free coming out.',
  resp: 'Attracts the 20% education grant. Contributions are not deductible.',
  rrsp: 'Deductible now, taxed on withdrawal — worth it while your rate now exceeds your rate later.',
  tfsa: 'No deduction, but nothing is taxed again — including in the benefit calculations.',
  non_registered: 'No shelter. Only reached once registered room is exhausted.',
};

interface PlannerResponse {
  taxYear: number;
  province: string;
  position: {
    taxable_income: number;
    afni: number;
    tax: number;
    household_tax: number;
    benefits: number;
    net_cash: number;
  };
  marginal: { statutory_rate: number; clawback_rate: number; effective_rate: number };
  benefits: { ccb: number; bcfb: number; pcb: number; cgeb: number; total: number };
  payroll: { cpp: number; cpp2: number; ei: number; total: number };
  allocation: {
    allocation: Record<string, number>;
    sequence: string[];
    total_deducted: number;
    tax_refund: number;
    benefit_restored: number;
    employer_match_earned: number;
    resp_grant_earned: number;
    warnings: string[];
  } | null;
  curve: Array<{ income: number; statutory_rate: number; clawback_rate: number; effective_rate: number }>;
  provinces: string[];
}

export function PlannerView() {
  const router = useRouter();
  const applyPlan = useWorkspace((s) => s.applyPlan);
  const [includeBoost, setIncludeBoost] = React.useState(false);
  const [province, setProvince] = React.useState('BC');
  const [income, setIncome] = React.useState(95_000);
  const [partnerIncome, setPartnerIncome] = React.useState(0);
  const [childAges, setChildAges] = React.useState<number[]>([3, 6]);
  const [savingsCapacity, setSavingsCapacity] = React.useState(20_000);
  const [fhsaEligible, setFhsaEligible] = React.useState(true);
  const [matchRate, setMatchRate] = React.useState(0.5);
  const [matchCap, setMatchCap] = React.useState(4_000);
  const [retirementRate, setRetirementRate] = React.useState(0.25);

  const [data, setData] = React.useState<PlannerResponse | null>(null);
  const [pending, setPending] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const controller = React.useRef<AbortController | null>(null);

  const compute = React.useCallback(async () => {
    controller.current?.abort();
    const ac = new AbortController();
    controller.current = ac;
    setPending(true);
    setError(null);
    try {
      const res = await fetch('/api/planner', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          province,
          income,
          partnerIncome,
          childAges,
          savingsCapacity,
          fhsaEligible,
          employerMatchRate: matchRate,
          employerMatchCap: matchCap,
          expectedRetirementRate: retirementRate,
        }),
        signal: ac.signal,
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? 'Could not compute.');
      if (!ac.signal.aborted) setData(json as PlannerResponse);
    } catch (e) {
      if (!ac.signal.aborted) setError(e instanceof Error ? e.message : 'Could not compute.');
    } finally {
      if (!ac.signal.aborted) setPending(false);
    }
  }, [province, income, partnerIncome, childAges, savingsCapacity, fhsaEligible, matchRate, matchCap, retirementRate]);

  // Recompute as inputs settle; the engine is pure arithmetic and fast.
  React.useEffect(() => {
    const t = setTimeout(() => void compute(), 350);
    return () => clearTimeout(t);
  }, [compute]);

  React.useEffect(() => () => controller.current?.abort(), []);

  const gap = data ? data.marginal.effective_rate - data.marginal.statutory_rate : 0;

  /**
   * Growth for the wrapper comparison, taken from a REAL backtest when one
   * exists.
   *
   * Time-weighted return is growth per dollar, which is exactly what is needed.
   * Falling back to a flat assumption is fine here and clearly labelled,
   * because the wrapper answer does not depend on the growth rate at all — the
   * factor cancels. It only sets how much is at stake.
   */
  const runs = useWorkspace((s) => s.runs);
  const growth = React.useMemo(() => {
    const usable = runs.find(
      (r) => r.summary && Number.isFinite(r.summary.totalReturn) && r.summary.finalValue > 0,
    );
    if (usable) {
      return {
        factor: 1 + usable.summary.totalReturn,
        label: `${usable.label}'s measured growth over ${usable.summary.start} to ${usable.summary.end}`,
      };
    }
    return {
      factor: 2.5,
      label: 'a placeholder 2.5x, because no backtest has been run — the ranking is unaffected',
    };
  }, [runs]);


  return (
    <>
      <PageHeader
        title="Tax &amp; benefits"
        description="What your next dollar is actually worth in Canada, and which account it belongs in."
        actions={
          data && <Badge variant="outline">{data.taxYear} tax year · {data.province}</Badge>
        }
      />

      <PageBody className="grid items-start gap-5 lg:grid-cols-[23rem_minmax(0,1fr)] xl:grid-cols-[25rem_minmax(0,1fr)]">
        <div className="space-y-5 lg:sticky lg:top-6">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle>Your situation</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1">
                <Label htmlFor="pl-prov">Province</Label>
                <Select value={province} onValueChange={setProvince}>
                  <SelectTrigger id="pl-prov" className="text-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(data?.provinces ?? ['BC']).map((p) => (
                      <SelectItem key={p} value={p}>
                        {p}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <MoneyField label="Your income" id="pl-income" value={income} onChange={setIncome} />
                <MoneyField
                  label="Partner income"
                  id="pl-partner"
                  value={partnerIncome}
                  onChange={setPartnerIncome}
                />
              </div>

              <div className="space-y-1">
                <div className="flex items-center gap-1.5">
                  <Label>Children</Label>
                  <InfoTip label="About children">
                    Ages matter: the Canada Child Benefit pays more under 6 and stops at 18, while
                    the groceries and essentials benefit counts children under 19.
                  </InfoTip>
                </div>
                <div className="flex flex-wrap items-center gap-1.5">
                  {childAges.map((age, i) => (
                    <span
                      key={i}
                      className="inline-flex items-center gap-1 rounded border border-border px-1.5 py-1 text-xs"
                    >
                      <input
                        type="number"
                        min="0"
                        max="29"
                        aria-label={`Age of child ${i + 1}`}
                        value={age}
                        onChange={(e) =>
                          setChildAges((prev) =>
                            prev.map((a, j) => (j === i ? Number(e.target.value) : a)),
                          )
                        }
                        className="numeric w-9 bg-transparent text-right outline-none"
                      />
                      <button
                        type="button"
                        aria-label={`Remove child ${i + 1}`}
                        onClick={() => setChildAges((prev) => prev.filter((_, j) => j !== i))}
                        className="text-muted-foreground hover:text-negative"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </span>
                  ))}
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 px-2 text-xs"
                    onClick={() => setChildAges((prev) => [...prev, 5])}
                  >
                    <Plus />
                    Add
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle>This year&rsquo;s savings</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <MoneyField
                label="Amount you can save"
                id="pl-capacity"
                value={savingsCapacity}
                onChange={setSavingsCapacity}
              />
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label htmlFor="pl-mrate">Employer match rate</Label>
                  <Input
                    id="pl-mrate"
                    type="number"
                    step="0.05"
                    min="0"
                    max="2"
                    value={matchRate}
                    onChange={(e) => setMatchRate(Number(e.target.value))}
                    className="text-xs"
                  />
                </div>
                <MoneyField label="Match cap" id="pl-mcap" value={matchCap} onChange={setMatchCap} />
              </div>
              <div className="space-y-1">
                <div className="flex items-center gap-1.5">
                  <Label htmlFor="pl-rrate">Expected rate in retirement</Label>
                  <InfoTip label="About the retirement rate">
                    An RRSP is worth using while your effective rate today is higher than the rate
                    you expect when you withdraw. Below that line, the TFSA comes first.
                  </InfoTip>
                </div>
                <Input
                  id="pl-rrate"
                  type="number"
                  step="0.01"
                  min="0"
                  max="1"
                  value={retirementRate}
                  onChange={(e) => setRetirementRate(Number(e.target.value))}
                  className="text-xs"
                />
              </div>
              <label className="flex cursor-pointer items-center gap-2 text-xs">
                <input
                  type="checkbox"
                  checked={fhsaEligible}
                  onChange={(e) => setFhsaEligible(e.target.checked)}
                  className="h-3.5 w-3.5 accent-[hsl(var(--primary))]"
                />
                Eligible for an FHSA (first-time home buyer)
              </label>
            </CardContent>
          </Card>
        </div>

        <div className="min-w-0 space-y-5">
          {error && (
            <div
              role="alert"
              className="flex items-start gap-3 rounded-lg border border-destructive/40 bg-destructive/8 p-4"
            >
              <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-negative" />
              <p className="text-xs leading-relaxed">{error}</p>
            </div>
          )}

          {!data && pending && <Skeleton className="h-64 w-full" />}

          {data && (
            <div className={cn('space-y-5', pending && 'opacity-60')}>
              <div className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-4">
                <Stat
                  className="bg-card"
                  size="lg"
                  label="Your posted rate"
                  value={formatPercent(data.marginal.statutory_rate, 1)}
                  sub="income tax alone"
                  hint="What the tax brackets say the next dollar costs."
                />
                <Stat
                  className="bg-card"
                  size="lg"
                  label="Benefit clawback"
                  tone={data.marginal.clawback_rate > 0 ? 'negative' : 'neutral'}
                  value={formatPercent(data.marginal.clawback_rate, 1)}
                  sub="withdrawn on the next dollar"
                  hint="Income-tested benefits reduce as income rises. This is how much of the next dollar they take back — it appears nowhere on a tax return."
                />
                <Stat
                  className="bg-card"
                  size="lg"
                  label="What it actually costs"
                  tone="negative"
                  value={formatPercent(data.marginal.effective_rate, 1)}
                  sub={gap > 0.01 ? `${formatPercent(gap, 1)} above the bracket` : 'matches the bracket'}
                  hint="Tax plus clawback: the true marginal cost of earning one more dollar."
                />
                <Stat
                  className="bg-card"
                  size="lg"
                  label="Benefits received"
                  tone="positive"
                  value={formatCurrency(data.benefits.total)}
                  sub="this year"
                />
              </div>

              {gap > 0.05 && (
                <div className="rounded-lg border border-[hsl(var(--warning))]/40 bg-[hsl(var(--warning))]/8 p-4 text-xs leading-relaxed">
                  Your posted bracket says{' '}
                  <span className="numeric font-semibold">
                    {formatPercent(data.marginal.statutory_rate, 1)}
                  </span>
                  , but the next dollar you earn actually costs you{' '}
                  <span className="numeric font-semibold">
                    {formatPercent(data.marginal.effective_rate, 1)}
                  </span>{' '}
                  once benefit withdrawal is counted — a gap of{' '}
                  <span className="numeric font-semibold">{formatPercent(gap, 1)}</span>. That also
                  means a deductible contribution is worth {formatPercent(data.marginal.effective_rate, 1)}{' '}
                  to you, not {formatPercent(data.marginal.statutory_rate, 1)}.
                </div>
              )}

              <MarginalCurve data={data} income={income} />

              {data.allocation && (
                <AllocationPanel
                  allocation={data.allocation}
                  savingsCapacity={savingsCapacity}
                  includeBoost={includeBoost}
                  setIncludeBoost={setIncludeBoost}
                  onBacktest={(boost) => {
                    const { config, assumptions } = planToBacktestConfig({
                      savingsCapacity,
                      firstYearBoost: boost,
                      includeBoost,
                    });
                    applyPlan(config, assumptions);
                    router.push('/backtest');
                  }}
                />
              )}

              {/* Where the plan and the backtest meet. */}
              <WrapperPanel
                contribution={savingsCapacity}
                growthFactor={growth.factor}
                rateNow={data.marginal.effective_rate}
                rateLater={retirementRate}
                growthLabel={growth.label}
              />

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle>Where the money goes</CardTitle>
                </CardHeader>
                <CardContent>
                  <dl className="grid grid-cols-2 gap-4 sm:grid-cols-4 text-xs">
                    <Figure label="Income tax" value={formatCurrency(data.position.household_tax)} />
                    <Figure
                      label="CPP, CPP2 and EI"
                      value={formatCurrency(data.payroll.total)}
                      hint="Levied on gross employment income. An RRSP deduction does not reduce them, which is why they are excluded from the marginal rate above."
                    />
                    <Figure label="Benefits received" value={formatCurrency(data.benefits.total)} />
                    <Figure
                      label="Net cash"
                      value={formatCurrency(data.position.net_cash)}
                      hint="Household income, less tax, plus benefits. Payroll deductions are shown separately and are not subtracted here."
                    />
                  </dl>
                  {data.benefits.total > 0 && (
                    <>
                      <Separator className="my-3" />
                      <p className="text-2xs text-muted-foreground">
                        Made up of{' '}
                        {[
                          data.benefits.ccb > 0 && `${formatCurrency(data.benefits.ccb)} Canada Child Benefit`,
                          data.benefits.bcfb > 0 && `${formatCurrency(data.benefits.bcfb)} BC Family Benefit`,
                          data.benefits.pcb > 0 && `${formatCurrency(data.benefits.pcb)} provincial child benefit`,
                          data.benefits.cgeb > 0 && `${formatCurrency(data.benefits.cgeb)} groceries and essentials benefit`,
                        ]
                          .filter(Boolean)
                          .join(', ')}
                        .
                      </p>
                    </>
                  )}
                </CardContent>
              </Card>

              <p className="text-2xs leading-relaxed text-muted-foreground">
                Figures use the {data.taxYear} federal and {data.province} parameters, each recorded
                with its source. This is a calculation, not tax advice, and it does not model every
                credit or deduction that may apply to you.
              </p>
            </div>
          )}
        </div>
      </PageBody>
    </>
  );
}

function MoneyField({
  label,
  id,
  value,
  onChange,
}: {
  label: string;
  id: string;
  value: number;
  onChange: (v: number) => void;
}) {
  return (
    <div className="space-y-1">
      <Label htmlFor={id}>{label}</Label>
      <div className="relative">
        <span className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">
          $
        </span>
        <Input
          id={id}
          type="number"
          min="0"
          step="1000"
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
          className="pl-6 text-xs"
        />
      </div>
    </div>
  );
}

function Figure({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div>
      <dt className="flex items-center gap-1 text-2xs uppercase tracking-wide text-muted-foreground">
        {label}
        {hint && <InfoTip label={`About ${label}`}>{hint}</InfoTip>}
      </dt>
      <dd className="numeric mt-0.5 text-sm font-medium">{value}</dd>
    </div>
  );
}

function MarginalCurve({ data, income }: { data: PlannerResponse; income: number }) {
  return (
    <ChartFrame
      title="What every dollar costs, across the income range"
      description="Income tax and benefit withdrawal stacked, with your position marked."
      footer="The spikes are real: they are where a benefit phases out. Earning into one of them can cost more than half of every additional dollar."
    >
      <div className="h-64 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={data.curve} margin={{ top: 8, right: 12, bottom: 4, left: 4 }}>
            <CartesianGrid {...GRID_PROPS} />
            <XAxis
              dataKey="income"
              {...AXIS_PROPS}
              tickFormatter={(v) => `$${Math.round(Number(v) / 1000)}k`}
              minTickGap={40}
            />
            <YAxis
              {...AXIS_PROPS}
              width={48}
              tickFormatter={(v) => `${(Number(v) * 100).toFixed(0)}%`}
            />
            <Area
              type="stepAfter"
              dataKey="statutory_rate"
              stackId="r"
              name="Income tax"
              stroke="hsl(var(--primary))"
              fill="hsl(var(--primary))"
              fillOpacity={0.45}
              isAnimationActive={false}
            />
            <Area
              type="stepAfter"
              dataKey="clawback_rate"
              stackId="r"
              name="Benefit clawback"
              stroke="hsl(var(--negative))"
              fill="hsl(var(--negative))"
              fillOpacity={0.45}
              isAnimationActive={false}
            />
            <ReferenceLine
              x={income}
              stroke="hsl(var(--foreground))"
              strokeDasharray="4 4"
              label={{ value: 'you', position: 'top', fontSize: 10, fill: 'hsl(var(--foreground))' }}
            />
            <Tooltip
              cursor={{ stroke: 'hsl(var(--muted-foreground))', strokeDasharray: '3 3' }}
              content={({ active, payload, label }) => {
                if (!active || !payload?.length) return null;
                const row = payload[0].payload as PlannerResponse['curve'][number];
                return (
                  <ChartTooltip
                    title={formatCurrency(Number(label))}
                    rows={[
                      { label: 'Income tax', value: formatPercent(row.statutory_rate, 1), color: 'hsl(var(--primary))' },
                      { label: 'Benefit clawback', value: formatPercent(row.clawback_rate, 1), color: 'hsl(var(--negative))' },
                      { label: 'Total', value: formatPercent(row.effective_rate, 1) },
                    ]}
                  />
                );
              }}
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>
    </ChartFrame>
  );
}

function AllocationPanel({
  allocation,
  savingsCapacity,
  includeBoost,
  setIncludeBoost,
  onBacktest,
}: {
  allocation: NonNullable<PlannerResponse['allocation']>;
  savingsCapacity: number;
  includeBoost: boolean;
  setIncludeBoost: (v: boolean) => void;
  onBacktest: (boost: number) => void;
}) {
  const entries = allocation.sequence
    .map((k) => [k, allocation.allocation[k] ?? 0] as const)
    .filter(([, v]) => v > 0);
  const total = entries.reduce((s, [, v]) => s + v, 0) || 1;
  const boost =
    allocation.tax_refund +
    allocation.benefit_restored +
    allocation.employer_match_earned +
    allocation.resp_grant_earned;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle>Where this year&rsquo;s savings should go</CardTitle>
        <p className="text-xs text-muted-foreground">
          In the order the solver actually funded them, re-scoring after each step as your effective
          rate moves.
        </p>
      </CardHeader>
      <CardContent className="space-y-4 px-0 pb-0">
        <div className="px-4 sm:px-5">
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            <Figure label="Tax refund" value={formatCurrency(allocation.tax_refund)} />
            <Figure
              label="Benefits restored"
              value={formatCurrency(allocation.benefit_restored)}
              hint="Deductible contributions lower family net income, which restores income-tested benefits. For families in a clawback band this is routinely larger than the refund."
            />
            <Figure label="Employer match" value={formatCurrency(allocation.employer_match_earned)} />
            <Figure label="Education grant" value={formatCurrency(allocation.resp_grant_earned)} />
          </div>
          {boost > 0 && (
            <p className="mt-3 rounded-md border border-border bg-muted/40 p-3 text-xs leading-relaxed">
              Funding it this way returns{' '}
              <span className="numeric font-semibold text-positive">{formatCurrency(boost)}</span>{' '}
              in the first year — refund, restored benefits, employer match and grant combined.
            </p>
          )}

          {/* The handoff: the plan sizes the contribution, the backtester shows
              what happens to it. */}
          <div className="mt-3 rounded-md border border-primary/30 bg-primary/5 p-3">
            <p className="text-xs font-medium">See what this becomes</p>
            <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
              Carry {formatCurrency(savingsCapacity)} a year into the backtester and run it against
              real market history.
            </p>
            {boost > 0 && (
              <label className="mt-2 flex cursor-pointer items-start gap-2 text-xs">
                <input
                  type="checkbox"
                  checked={includeBoost}
                  onChange={(e) => setIncludeBoost(e.target.checked)}
                  className="mt-0.5 h-3.5 w-3.5 accent-[hsl(var(--primary))]"
                />
                <span>
                  Also contribute the {formatCurrency(boost)} of refund, benefits and match each
                  year. This assumes you reinvest it rather than spend it — which is the difference
                  between a plan and a habit.
                </span>
              </label>
            )}
            <Button size="sm" className="mt-2.5" onClick={() => onBacktest(boost)}>
              <LineChart />
              Backtest this plan
            </Button>
          </div>
        </div>

        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Order</TableHead>
              <TableHead>Account</TableHead>
              <NumHead>Amount</NumHead>
              <NumHead>Share</NumHead>
              <TableHead>Why</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {entries.map(([account, amount], i) => (
              <TableRow key={account}>
                <NumCell className="text-left text-xs text-muted-foreground">{i + 1}</NumCell>
                <TableCell className="whitespace-nowrap text-xs font-medium">
                  {ACCOUNT_LABELS[account] ?? account}
                </TableCell>
                <NumCell className="text-xs font-medium">{formatCurrency(amount)}</NumCell>
                <NumCell className="text-xs text-muted-foreground">
                  {formatPercent(amount / total, 0)}
                </NumCell>
                <TableCell className="max-w-[22rem] text-2xs leading-relaxed text-muted-foreground">
                  {ACCOUNT_WHY[account]}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>

        {allocation.warnings.length > 0 && (
          <div className="space-y-2 px-4 pb-4 sm:px-5">
            {allocation.warnings.map((w) => (
              <div
                key={w}
                className="flex items-start gap-2 rounded-md border border-[hsl(var(--warning))]/40 bg-[hsl(var(--warning))]/8 p-2.5 text-xs leading-relaxed"
              >
                <Calculator className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[hsl(var(--warning))]" />
                <span>{w}</span>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
