import { describe, expect, it } from 'vitest';
import fixtures from './fixtures/canpath-fixtures.json';
import {
  bracketTax,
  combinedTax,
  payrollDeductions,
  provincialTax,
  TAX_CONFIG,
} from '../src/lib/canpath/tax';
import { provincialChildBenefit, totalBenefits } from '../src/lib/canpath/benefits';
import {
  effectiveMarginalRate,
  netPosition,
  valueOfContribution,
} from '../src/lib/canpath/position';
import { optimize } from '../src/lib/canpath/allocate';
import {
  cppBreakevenAge,
  cppEstimate,
  depletionYears,
  futureValue,
  realRate,
  requiredMonthly,
} from '../src/lib/canpath/projection';
import type { Household } from '../src/lib/canpath/types';

/**
 * Parity against CanPath's Python reference engine.
 * =============================================================================
 * `fixtures.json` is generated by `tools/gen_fixtures.py` from the Python
 * engine, which is the source of truth for every figure in this application.
 * This suite replays all of it against the TypeScript port.
 *
 * This is the test that makes the port trustworthy. Hand-checking Canadian tax
 * arithmetic is not feasible at this scale — 230 cases spanning nine provinces,
 * four benefits and a funding-order solver — so the expected values come from
 * an independent implementation rather than from this codebase.
 *
 * Money is rounded to 2 decimals in the fixtures and rates to 6, so the
 * tolerances below match the reference's own rounding exactly. A port that
 * merely rounds to the same place would not pass; the intermediate arithmetic
 * has to agree.
 */


/**
 * Fixture values are stored ALREADY ROUNDED by the Python reference, so the
 * most precision any comparison can demand is half of the last stored digit.
 *
 * `toBeCloseTo` is the wrong tool here: it applies a strict `< 0.005`, while a
 * computed value landing exactly on the rounding boundary sits at exactly
 * 0.005 — and Python's `round()` is banker's rounding, so 37.125 is stored as
 * 37.12 rather than 37.13. Five of the 230 cases land on that boundary. The
 * epsilon absorbs the floating-point representation of the exact half.
 */
function agrees(actual: number, expected: number, places: number): void {
  const tolerance = 0.5 * 10 ** -places + 1e-9;
  const diff = Math.abs(actual - expected);
  if (diff > tolerance) {
    throw new Error(
      `expected ${actual} to agree with reference ${expected} to ${places} dp ` +
        `(difference ${diff}, tolerance ${tolerance})`,
    );
  }
}

/** Money, stored to 2 decimals. */
const money = (actual: number, expected: number) => agrees(actual, expected, 2);
/** Rates, stored to 6 decimals. */
const rate = (actual: number, expected: number) => agrees(actual, expected, 6);

const BC = (childAges: number[], partnerIncome = 0): Household => ({
  province: 'BC',
  child_ages: childAges,
  partner_income: partnerIncome,
});

describe('parity: fixture provenance', () => {
  it('is generated from the Python reference, for the year the data file states', () => {
    expect(fixtures.generated_by).toContain('python reference engine');
    expect(fixtures.tax_year).toBe(TAX_CONFIG.tax_year);
  });

  it('covers every province the data file supports', () => {
    const covered = new Set(fixtures.province_cases.map((c) => c.province));
    for (const code of Object.keys(TAX_CONFIG.provinces)) {
      expect(covered.has(code)).toBe(true);
    }
  });
});

describe('parity: provincial and combined tax', () => {
  it.each(fixtures.province_cases)(
    '$province at $income',
    ({ province, income, prov_tax, combined_tax, effective_rate }) => {
      money(provincialTax(income, province), prov_tax);
      money(combinedTax(income, province), combined_tax);

      const emr = effectiveMarginalRate(income, {
        province,
        child_ages: [],
        partner_income: 0,
      });
      rate(emr.effective_rate, effective_rate);
    },
  );
});

describe('parity: payroll deductions', () => {
  it.each(fixtures.payroll_cases)('income $income', ({ income, cpp, cpp2, ei, total }) => {
    const d = payrollDeductions(income);
    money(d.cpp, cpp);
    money(d.cpp2, cpp2);
    money(d.ei, ei);
    money(d.total, total);
  });
});

describe('parity: provincial child benefits', () => {
  // Two children aged 4 and 8, partnered with no partner income — the case the
  // reference generates across every province at every band edge.
  it.each(fixtures.pcb_cases)('$province at $afni', ({ province, afni, pcb, total }) => {
    money(provincialChildBenefit(afni, [4, 8], province), pcb);

    const household: Household = {
      province,
      child_ages: [4, 8],
      partner_income: 0,
      partnered: true,
    };
    money(totalBenefits(afni, household).total, total);
  });
});

describe('parity: net position and marginal rate', () => {
  it.each(fixtures.marginal_cases)(
    'income $income, partner $partner_income, children $child_ages',
    (c) => {
      const household = BC(c.child_ages, c.partner_income);

      const pos = netPosition(c.income, household);
      money(pos.afni, c.afni);
      money(pos.tax, c.tax);
      money(pos.benefits, c.benefits_total);

      // Split out per benefit, so a regression in any one is attributable
      // rather than buried in a total that happens to still add up.
      const split = totalBenefits(pos.afni, household);
      money(split.ccb, c.benefit_split.ccb);
      money(split.bcfb, c.benefit_split.bcfb);
      money(split.pcb, c.benefit_split.pcb);
      money(split.cgeb, c.benefit_split.cgeb);
      money(split.total, c.benefit_split.total);

      const emr = effectiveMarginalRate(c.income, household);
      rate(emr.statutory_rate, c.statutory_rate);
      rate(emr.clawback_rate, c.clawback_rate);
      rate(emr.effective_rate, c.effective_rate);

      const val = valueOfContribution(c.income, 10_000, household);
      money(val.tax_refund, c.value_10k_tax_refund);
      money(val.benefit_restored, c.value_10k_benefit);
    },
  );
});

describe('parity: allocation solver', () => {
  it.each(fixtures.allocation_cases)(
    'income $income, capacity $capacity, children $child_ages',
    (c) => {
      const result = optimize({
        income: c.income,
        household: BC(c.child_ages, 0),
        savings_capacity: c.capacity,
        expected_retirement_rate: c.retirement_rate,
        fhsa_eligible: c.fhsa_eligible,
        employer_match_rate: c.match_rate,
        employer_match_cap: c.match_cap,
      });

      // Same accounts funded, same amounts — the solver re-scores after every
      // chunk, so any drift in the marginal rate would reorder this.
      const expected = c.allocation as unknown as Record<string, number>;
      expect(Object.keys(result.allocation).sort()).toEqual(Object.keys(expected).sort());
      for (const [account, amount] of Object.entries(expected)) {
        money(result.allocation[account as keyof typeof result.allocation] ?? 0, amount);
      }

      money(result.total_deducted, c.total_deducted);
      money(result.tax_refund, c.tax_refund);
      money(result.benefit_restored, c.benefit_restored);
      money(result.resp_grant_earned, c.resp_grant_earned);
      money(result.rrsp_room_used + result.rrsp_room_left, c.rrsp_room);
    },
  );
});

describe('bracket arithmetic', () => {
  it('applies each rate only to the income inside its own band', () => {
    const brackets = [
      { floor: 0, rate: 0.1 },
      { floor: 100, rate: 0.2 },
      { floor: 200, rate: 0.3 },
    ];
    expect(bracketTax(0, brackets)).toBe(0);
    expect(bracketTax(50, brackets)).toBeCloseTo(5, 10);
    expect(bracketTax(100, brackets)).toBeCloseTo(10, 10);
    // 100 at 10% + 50 at 20%.
    expect(bracketTax(150, brackets)).toBeCloseTo(20, 10);
    // 100 at 10% + 100 at 20% + 100 at 30%.
    expect(bracketTax(300, brackets)).toBeCloseTo(60, 10);
  });

  it('treats negative income as zero tax rather than a refund', () => {
    expect(bracketTax(-5000, TAX_CONFIG.federal.brackets)).toBe(0);
    expect(combinedTax(-5000, 'BC')).toBe(0);
  });

  it('rejects a province the data file does not cover', () => {
    expect(() => provincialTax(50_000, 'ZZ')).toThrow(/not supported/);
  });
});

describe('parity: projection engine', () => {
  it.each(fixtures.projection_cases)(
    'principal $principal, monthly $monthly, $rate over $years years',
    ({ principal, monthly, rate: r, years, fv, real_rate: rr, fv_real, req_monthly }) => {
      agrees(futureValue(principal, monthly, r, years), fv, 4);
      agrees(realRate(r, 0.02), rr, 8);
      agrees(futureValue(principal, monthly, realRate(r, 0.02), years), fv_real, 4);
      agrees(requiredMonthly(500_000, principal, r, years), req_monthly, 4);
    },
  );

  it.each(fixtures.depletion_cases)(
    'balance $balance drawing $draw at $rate',
    ({ balance, draw, rate: r, years }) => {
      expect(depletionYears(balance, draw, r)).toBe(years);
    },
  );

  it.each(fixtures.cpp_breakeven_cases)(
    'CPP from $early versus $late',
    ({ early, late, early_annual, late_annual, breakeven_age }) => {
      agrees(cppEstimate(early), early_annual, 4);
      agrees(cppEstimate(late), late_annual, 4);
      agrees(cppBreakevenAge(early, late), breakeven_age, 1);
    },
  );
});
