import sys, json
sys.path.insert(0, "/home/claude/asts")
import build_xlsx as B
from build_xlsx import put, title, section, setw, FMT, BOLD, BLACK, BLUE, GREEN, GREY, HDR, FILL_H, FILL_S, FILL_Y, CL
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.chart.series import SeriesLabel
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Alignment, Font
import inputs as I

A = json.load(open("/home/claude/asts/analytics.json"))
wb = B.wb
VS, MS, WR = B.VS, B.MS, B.WR
STAMP = f"Generated by analytics.py (seed {A['seed']}, {A['n']:,} paths) on 10-Sep-2026 from Base inputs as delivered. Values, not formulas: re-run to refresh."
WRAP = Alignment(wrap_text=True, vertical="top")

# ======================= Sensitivity: stamped tables
wsS = wb["Sensitivity"]
r = B.SENS_STAMP_ROW
put(wsS, f"A{r}", "Tornado - Base value per share at P10 / P90 of each driver (engine.py)", BOLD)
put(wsS, f"A{r+1}", STAMP, GREY); r += 2
for j, h in enumerate(["Driver", "P10 input", "$/sh at P10", "P90 input", "$/sh at P90", "Swing $"]):
    put(wsS, f"{CL(1+j)}{r}", h, HDR, fill=FILL_H)
r += 1; t0 = r
for nm, desc, lo, vlo, hi, vhi, sw in A["tornado"]:
    put(wsS, f"A{r}", nm); put(wsS, f"B{r}", lo, BLUE, "0.000"); put(wsS, f"C{r}", vlo, BLUE, "$")
    put(wsS, f"D{r}", hi, BLUE, "0.000"); put(wsS, f"E{r}", vhi, BLUE, "$"); put(wsS, f"F{r}", sw, BLUE, "$"); r += 1
put(wsS, f"A{r}", f"Base value per share (reference): ${A['base_v']:.2f}", GREY)
ch = BarChart(); ch.type = "bar"; ch.title = "Tornado: swing in Base $/share (P10-P90)"; ch.style = 10
ch.add_data(Reference(wsS, min_col=6, min_row=t0 - 1, max_row=r - 1), titles_from_data=True)
ch.set_categories(Reference(wsS, min_col=1, min_row=t0, max_row=r - 1)); ch.height = 8; ch.width = 14; ch.legend = None
ch.y_axis.title = "$ per share"; ch.x_axis.scaling.orientation = "maxMin"
wsS.add_chart(ch, "J15")
r += 2


def grid(r, ttl, rlab, rows, clab, cols, data, rfmt, cfmt):
    put(wsS, f"A{r}", ttl, BOLD); put(wsS, f"A{r+1}", STAMP, GREY); r += 2
    put(wsS, f"A{r}", f"{rlab} (rows) / {clab} (cols)", GREY)
    for j, c in enumerate(cols):
        put(wsS, f"{CL(2+j)}{r}", c, BOLD, cfmt)
    for i, rv in enumerate(rows):
        put(wsS, f"A{r+1+i}", rv, BOLD, rfmt)
        for j in range(len(cols)):
            put(wsS, f"{CL(2+j)}{r+1+i}", data[i][j], BLUE, "$")
    rng = f"B{r+1}:{CL(1+len(cols))}{r+len(rows)}"
    wsS.conditional_formatting.add(rng, ColorScaleRule(start_type="min", start_color="F8696B", mid_type="percentile",
                                                       mid_value=50, mid_color="FFEB84", end_type="max", end_color="63BE7B"))
    return r + len(rows) + 2


r = grid(r, "Base $/share: Tier-1 peak take rate x Tier-1 ARPU", "Take rate", [0.04, 0.06, 0.08, 0.10, 0.12, 0.15, 0.20],
         "ARPU $/mo", [3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5], A["g1"], "0%", "$0.00")
r = grid(r, "Base $/share: satellite unit cost x CIP pre-funding share", "Unit cost $mm", [20, 22, 24, 26, 28],
         "CIP credit", [0.25, 0.4, 0.5, 0.6, 0.75], A["g2"], "0", "0%")
take, shift, whi, wt, mult = A["rev"]
put(wsS, f"A{r}", "Reverse DCF - what the $%.2f share price implies (engine.py)" % A["price"], BOLD); r += 1
for lab, v, f in [("Base-case Tier-1 peak take rate that equates value to price", take, "0.0%"),
                  ("Base-case parallel WACC shift that equates value to price", shift, "0.00%"),
                  ("  implied growth-phase WACC", whi, "0.00%"), ("  implied terminal WACC", wt, "0.00%"),
                  ("Multiplier on every scenario's Tier-1 take rate for prob-weighted value = price", mult, "0.00x")]:
    put(wsS, f"A{r}", lab); put(wsS, f"E{r}", v, BLUE, f); r += 1
setw(wsS, {"A": 62})

# ======================= Monte Carlo sheet
wsMC = wb.create_sheet("Monte_Carlo")
title(wsMC, "MONTE CARLO SIMULATION", STAMP)
setw(wsMC, {"A": 50, "B": 14, "C": 14, "D": 70})
r = 4; section(wsMC, r, "Design (Agent 2)", 4); r += 1
for lab, v in [("Engine", "engine.py run() on Base inputs; Distress jump with scenario probability"),
               ("Paths", f"{A['n']:,}"), ("Random seed", A["seed"]),
               ("Dependence", "Gaussian copula; correlation matrix below (PSD: min eigenvalue %.3f)" % A["eig_min"]),
               ("Distress jump probability", A["p_distress"]),
               ("Beta / WACC", "Live Blume beta; WACC shift drawn N(0,1pp)")]:
    put(wsMC, f"A{r}", lab); put(wsMC, f"B{r}", v, BLUE, "0%" if lab.startswith("Distress") else None); r += 1
r += 1; put(wsMC, f"A{r}", "Driver", HDR, fill=FILL_H); put(wsMC, f"B{r}", "Distribution", HDR, fill=FILL_H); r += 1
for nm, desc in A["dists"]:
    put(wsMC, f"A{r}", nm); put(wsMC, f"B{r}", desc); r += 1
r += 1; put(wsMC, f"A{r}", "Correlation pair", HDR, fill=FILL_H); put(wsMC, f"B{r}", "rho", HDR, fill=FILL_H)
put(wsMC, f"D{r}", "Rationale", HDR, fill=FILL_H); r += 1
rat = {("take_t1", "take_t2"): "Common demand factor for D2D.", ("take_t1", "arpu_t1"): "Price elasticity: cheaper plans lift take-up.",
       ("take_t2", "arpu_t2"): "Price elasticity.", ("unit_cost", "delay"): "Programme stress raises cost and slips schedule together.",
       ("delay", "take_t1"): "Late network cedes share to Starlink D2C."}
for a, b, rho in A["corr"]:
    put(wsMC, f"A{r}", f"{a} / {b}"); put(wsMC, f"B{r}", rho, BLUE, "0.00"); put(wsMC, f"D{r}", rat[(a, b)], GREY); r += 1
r += 1; section(wsMC, r, "Results - value per share ($)", 4); r += 1
MC = {}
res = [("Mean", A["mean"], "$", "mean"), ("Std. error of mean", A["se"], "$", "se"), ("P5", A["pct"]["5"], "$", "p5"),
       ("P10", A["pct"]["10"], "$", "p10"), ("P25", A["pct"]["25"], "$", "p25"), ("Median", A["pct"]["50"], "$", "p50"),
       ("P75", A["pct"]["75"], "$", "p75"), ("P90", A["pct"]["90"], "$", "p90"), ("P95", A["pct"]["95"], "$", "p95"),
       ("P(value > current price)", A["p_above"], "0.0%", "pab"), ("P(equity value ~ 0)", A["p_zero"], "0.0%", "pz"),
       ("Mean excluding distress paths", A["mean_nondistress"], "$", "mnd"),
       ("Scenario prob-weighted value (for triangulation)", A["pw"], "$", "pw"),
       ("Current price", A["price"], "$", "px")]
for lab, v, f, k in res:
    put(wsMC, f"A{r}", lab); put(wsMC, f"B{r}", v, BLUE, f); MC[k] = f"Monte_Carlo!$B${r}"; r += 1
put(wsMC, f"A{r}", "MC mean / scenario prob-weighted - 1"); put(wsMC, f"B{r}", f"={MC['mean'].split('!')[1]}/{MC['pw'].split('!')[1]}-1", BLACK, "0.0%")
put(wsMC, f"D{r}", "Two independent aggregation methods; agreement within ~5% (A2-05).", GREY); r += 1
put(wsMC, f"A{r}", "Model-implied expected return p.a. (3-yr convergence, on MC mean)")
put(wsMC, f"B{r}", f"=({MC['mean'].split('!')[1]}*(1+{WR['ke_hi']})^3/{MC['px'].split('!')[1]})^(1/3)-1", BLACK, "0.0%")
MC["er3"] = f"Monte_Carlo!$B${r}"; r += 2
put(wsMC, f"A{r}", "Convergence: running mean by path count", BOLD); r += 1
for k, v in A["conv"].items():
    put(wsMC, f"A{r}", f"First {int(k):,} paths"); put(wsMC, f"B{r}", v, BLUE, "$"); r += 1
r += 1; put(wsMC, f"A{r}", "Histogram bin ($, lower edge)", HDR, fill=FILL_H); put(wsMC, f"B{r}", "Paths", HDR, fill=FILL_H); r += 1
h0 = r
for i, cnt in enumerate(A["hist"]):
    put(wsMC, f"A{r}", f"{i*10}-{i*10+10}" if i < len(A["hist"]) - 1 else "290+"); put(wsMC, f"B{r}", cnt, BLUE, "#"); r += 1
ch = BarChart(); ch.type = "col"; ch.title = "Distribution of value per share (20,000 paths)"; ch.style = 10
ch.add_data(Reference(wsMC, min_col=2, min_row=h0 - 1, max_row=r - 1), titles_from_data=True)
ch.set_categories(Reference(wsMC, min_col=1, min_row=h0, max_row=r - 1)); ch.legend = None; ch.height = 8; ch.width = 18
ch.x_axis.title = "$ per share"; ch.y_axis.title = "paths"; ch.gapWidth = 10
wsMC.add_chart(ch, "D22")

# ======================= Risk sheet
wsR = wb.create_sheet("Risk")
title(wsR, "RISK ANALYSIS", "Market risk live from IBKR data; fundamental risk live from Calc sheets; simulation risk from Monte_Carlo.")
setw(wsR, {"A": 52, "B": 14, "C": 14, "D": 14, "E": 14, "F": 64})
r = 4; section(wsR, r, "Market risk (live)", 6); r += 1
for lab, k, f in [("Annualised volatility (2y weekly)", "vol", "%"), ("Idiosyncratic volatility", "idio", "%"),
                  ("Raw beta / std. error", "beta_raw", "f"), ("R-squared vs S&P 500", "r2", "%"),
                  ("Max drawdown (2y)", "mdd", "%"), ("1-week VaR 95% (historical)", "var95", "%"),
                  ("1-week CVaR 95%", "cvar95", "%"), ("1-week VaR 95% (parametric)", "pvar95", "%"),
                  ("Downside deviation (annualised)", "dd", "%")]:
    put(wsR, f"A{r}", lab); put(wsR, f"B{r}", f"={MS[k]}", GREEN, f)
    if k == "beta_raw": put(wsR, f"C{r}", f"={MS['beta_se']}", GREEN, "f")
    r += 1
put(wsR, f"A{r}", "Expected return / volatility (model-implied Sharpe, 3-yr)")
put(wsR, f"B{r}", f"=(Valuation_Summary!F{VS['er3']}-{B.IREF('rf')})/{MS['vol']}", BLACK, "0.00")
put(wsR, f"F{r}", "Inputs for the portfolio optimisation: replace the 12% placeholder with the model-implied figure.", GREY); r += 2
section(wsR, r, "Funding & balance-sheet risk (live, by scenario)", 6); r += 1
for s in range(4):
    put(wsR, f"{CL(2+s)}{r}", I.SCEN[s], BOLD)
r += 1
avail = f"({B.CASHREF}-Capital_Structure!B{[i for i in range(1, 200) if B.wb['Capital_Structure'][f'A{i}'].value == 'UBS bridge loan (cash-collateralised)'][0]})"
put(wsR, f"A{r}", "Available liquidity (cash less collateralised UBS loan)")
for s in range(4): put(wsR, f"{CL(2+s)}{r}", f"={avail}", GREEN, "$mm")
LQ = r; r += 1
put(wsR, f"A{r}", "Peak cumulative FCFF need")
for s in range(4): put(wsR, f"{CL(2+s)}{r}", f"=Calc_{I.SCEN[s]}!C{B.CALC_ROWS[s]['minfcf']}", GREEN, "$mm")
r += 1
put(wsR, f"A{r}", "Funding headroom / (gap) before new capital", BOLD)
for s in range(4): put(wsR, f"{CL(2+s)}{r}", f"={CL(2+s)}{LQ}+{CL(2+s)}{r-1}", BOLD, "$mm")
put(wsR, f"F{r+1}", "A3-10: excludes the committed $550mm non-recourse SPV facility for the Ligado payment (10-K) - adds ~$550mm headroom if drawn.", GREY)
put(wsR, f"F{r}", "Gap = equity/debt raise needed. Dilutive if raised below intrinsic value (not modelled; FCFF assumes fair-value raises).", GREY)
r += 2; section(wsR, r, "Convertible maturity wall", 6); r += 1
for lab, dt, amt in [("2032 4.25% converts", "1-Mar-2032", 3.514), ("2032 2.375% converts", "15-Oct-2032", 325.0),
                     ("2034 1.625% converts", "1-Feb-2034", 1150.0), ("2036 2.00% converts", "15-Jan-2036", 1150.0),
                     ("2036 2.25% converts", "15-Apr-2036", 1075.0)]:
    put(wsR, f"A{r}", lab); put(wsR, f"B{r}", dt); put(wsR, f"C{r}", amt, BLUE, "$mm"); r += 1
put(wsR, f"F{r-5}", "Sources: 10-Q Note 6; Feb-2026 8-K; Jul-2026 8-K. Converts settle in cash/shares at company election.", GREY)
r += 1; section(wsR, r, "Simulation risk (Monte_Carlo)", 6); r += 1
for lab, k, f in [("P(intrinsic value > price)", "pab", "0.0%"), ("P(equity value ~ 0)", "pz", "0.0%"),
                  ("P10 value per share", "p10", "$"), ("P90 value per share", "p90", "$")]:
    put(wsR, f"A{r}", lab); put(wsR, f"B{r}", f"={MC[k]}", GREEN, f); r += 1
r += 1; section(wsR, r, "Risk register (qualitative -> model lever)", 6); r += 1
for h, c in zip(["Risk", "Model lever(s)", "", "", "", "Evidence / comment"], "ABCDEF"):
    if h: put(wsR, f"{c}{r}", h, BOLD)
r += 1
reg = [("Deployment slip / launch failure", "fl_*, loss_rate, MC delay", "BB7 lost Apr-2026; history of Block 2 slips."),
       ("Adoption below plan (Starlink D2C competition)", "take_t1/t2, px_g", "T-Satellite $10/mo, 650+ Starlink sats; #1 value driver."),
       ("Spectrum / regulatory (Ligado FCC approval)", "ligado_year, spec_fee", "Application 'Pending Review' since Jan-2026."),
       ("Capital intensity / funding at depressed prices", "Funding gap rows above", "Dilution below value is value-destructive; not in FCFF."),
       ("Satellite life shorter than 7 yrs", "sat_life", "Secondary source only; drives replacement capex."),
       ("SBC-driven dilution", "sbc_* rows", "Q2-26 SBC $63.5mm/qtr; treated as cost."),
       ("Key-person / governance (Up-C, Class C control)", "Not modelled", "Founder controls via Class C voting shares.")]
for a_, b_, c_ in reg:
    put(wsR, f"A{r}", a_); put(wsR, f"B{r}", b_); put(wsR, f"F{r}", c_, GREY); r += 1

# ======================= Review log
wsL = wb.create_sheet("Review_Log")
title(wsL, "REVIEW LOG - agent findings, challenges and resolutions",
      "A1 = Lead Financial Analyst, A2 = Quant/Data Analyst, A3 = Senior Model Reviewer. One model ran all three roles; "
      "reviews were made real via an independently coded engine and executable tests.")
setw(wsL, {"A": 7, "B": 7, "C": 44, "D": 62, "E": 62, "F": 11})
for j, h in enumerate(["ID", "Raised", "Finding / challenge", "Evidence & reasoning", "Resolution", "Status"]):
    put(wsL, f"{CL(1+j)}4", h, HDR, fill=FILL_H)
ct = A["capex_timing"]
LOG = [
    ("R-01", "A2", "Regression beta is statistically weak; A3 separately argued ~10.5% Ke is too low for a pre-commercial firm.",
     "Raw beta 1.42, SE 0.60 (95% CI 0.24-2.60), R2 5%; yr1 1.04 vs yr2 2.17. CAPM prices only systematic risk.",
     "Blume-adjusted beta (1.28), live from IBKR data. Failure risk handled via explicit Distress/Bear scenarios, not a hand-inflated rate (avoids double count). WACC+/-2pp shown live.", "Resolved"),
    ("R-02", "A2", "Final weekly bar is a partial week.", "Bar dated 8-Sep-2026 closes mid-week.",
     "Excluded from regression and vol; retained as current price.", "Resolved"),
    ("R-03", "A2", "Should Bear/Distress carry higher WACCs?", "Scenario dispersion is cash-flow risk; CAPM rate should not vary by scenario.",
     "Single WACC path for all scenarios.", "Resolved"),
    ("R-04", "A3", "$1,724mm of satellite CIP is already paid: ignoring it double-counts capex; full credit may overstate.",
     "CIP also holds NRE, early-unit overruns and later launch deposits (10-Q Note 4).",
     "Base credits 50% (MC 25-75%). Tornado: +/- ~$1/sh - second-order.", "Resolved"),
    ("R-05", "A3", "Up-C: Class B/C shares represent exchangeable AST LLC units.", "Using Class A only (299.8mm) would overstate $/sh by ~30%.",
     "S0 = A+B+C = 389.2mm; check ties to 10-Q cover.", "Resolved"),
    ("R-06", "A3", "SBC ($63.5mm/qtr) must not be added back.", "SBC is a real transfer to employees.",
     "SBC deducted in EBITDA/FCFF; existing unvested RSUs also counted in shares (small overlap - conservative).", "Resolved"),
    ("R-07", "A3", "Convert dilution depends on value per share -> circularity risk.", "Excel circular refs are fragile and order-dependent if sorted.",
     "Proved: prefix converts iff value-with-prefix > its K; SUMIF formulation is order-independent, no circular refs. Verified in 12 break tests.", "Resolved"),
    ("R-08", "A3", "Restricted cash $428.4mm is collateral for $420mm UBS bridge.", "10-Q Note 3.",
     "Both included so they net; excluded from 'available liquidity' in Risk.", "Resolved"),
    ("R-09", "A1", "2034 notes carry a capped call ($79.57 -> $149.20).", "Pricing 8-K Jul-2026.",
     "Trigger = cap, D = n x cap. Capped-call time value and 2.375% capped call ignored (conservative).", "Documented"),
    ("R-10", "A3", "Contract liabilities ($266.9mm) are revenue already received in cash.", "10-Q revenue note.",
     "Deducted as non-cash revenue unwind over 2027-31.", "Resolved"),
    ("R-11", "A1", "Ligado spectrum commitments missing from naive models.", "10-K: $550mm at closing, >= $80mm/yr, revenue share.",
     "Included; revenue-share % not disclosed (3% placeholder, flagged).", "Open (data)"),
    ("A3-01", "A3", "Explicit revenue declined 2036-40 while TV assumed +2.5%.", "ARPU erosion applied forever; adoption saturated.",
     "Repricing limited to 2027-32; long-run ARPU +1.5%, partner base +1%. Live CAGR-vs-g check added.", "Fixed"),
    ("A3-02", "A3", "Base EBITDA margin 61-65% exceeded Iridium 56.8%.", "Network costs did not scale with fleet.",
     "Added $2mm/sat/yr network opex. Remaining 64% accepted (pure wholesale model); 40-75% bound check.", "Fixed"),
    ("A2-01", "A2", "Bear EV turned negative; DCF forces uneconomic reinvestment.", "No abandonment option in a fixed-plan DCF.",
     "Equity floored at 0 (limited liability); Distress/Bear values are conservative lower bounds.", "Documented"),
    ("A2-02", "A2", "Iridium benchmark is survivorship-biased.", "Original Iridium, Globalstar, ORBCOMM all went bankrupt.",
     "40% combined probability on Distress+Bear (both ~$0-1/sh).", "Resolved"),
    ("A2-03", "A2", "Terminal year sits on a lumpy replacement wave.", "Replacements cluster 2033-35, 2040.",
     "TV uses normalised replacement capex = fleet / life / (1-loss) x unit cost.", "Resolved"),
    ("A2-04", "A2", "Revenue must respect network capacity.", "Block 2: ~2,000 cells/sat.",
     "Users-per-satellite plausibility check (<= 2.5mm); Base peak ~1.6mm.", "Resolved"),
    ("A3-03", "A3", "Capex timed at launch, not when paid.", f"Test: paying one period earlier = {ct[2]:,.0f} $mm PV.",
     f"Base ${ct[0]:.2f} -> ${ct[1]:.2f} ({ct[1]/ct[0]-1:+.1%}). Documented, not modelled.", "Documented"),
    ("A3-04", "A3", "Checks passed on first run - are they capable of failing?", "Untested tests prove nothing.",
     "12 break-tests (stress.py): every intended check fired; workbook = engine to 1e-14 in all cases.", "Resolved"),
    ("A3-05", "A3", "Sensitivity g-axis hard-coded; grid silently de-centred when g changed.", "Surfaced by g = 6% break test.",
     "Axis now = live g +/- offsets; centre check holds.", "Fixed"),
    ("A2-05", "A2", "Triangulate scenario weighting vs simulation.", f"MC mean ${A['mean']:.2f} vs prob-weighted ${A['pw']:.2f}.",
     "Agreement within 5%; both reported.", "Resolved"),
    ("A2-06", "A2", "MC robustness.", f"Correlation matrix PSD (min eig {A['eig_min']:.2f}); SE of mean ${A['se']:.2f}; running mean converged.",
     "20,000 paths, fixed seed - reproducible.", "Resolved"),
    ("A3-06", "A3", "Stale equity-award counts.", "AST LLC options (Jun-2025) and 2024-Plan RSUs (Dec-2025) are latest found.",
     "Flagged in Capital_Structure. Each +1mm shares ~ -0.25% per share.", "Open (data)"),
    ("A3-07", "A3", "Possible Tax Receivable Agreement (common in Up-C).", "Not confirmed in sources reviewed.",
     "Not modelled; would reduce value if present. Confirm in 10-K.", "Open (data)"),
    ("A3-08", "A3", "Look-ahead / anchoring bias.", "All inputs dated <= 10-Sep-2026.",
     "No parameter calibrated to price; reverse DCF reported separately.", "Pass"),
    ("A2-07", "A2", "Overfitting.", "Only beta estimated from history; shown with SE.", "No curve-fitting of forecasts.", "Pass"),
    ("A3-09", "A3", "Currency consistency.", "All figures USD (NASDAQ, SEC filings); holder reports in CAD.",
     "Model in USD; convert at spot for portfolio use.", "Documented"),
    ("A3-10", "A3", "Liquidity test ignores committed financing for the Ligado payment.", "10-K: $550mm non-recourse delayed-draw SPV commitment.",
     "Noted on Risk sheet (Base headroom -$78mm -> ~+$472mm with facility). Valuation unaffected (FCFF).", "Documented"),
    ("A3-11", "A3", "Probability-weighting EV mixes in negative Distress EV (-$12bn).", "Violates limited liability; averages a non-claim.",
     "Only floored per-share values are weighted; weighted EV/equity removed from summary and dashboard.", "Fixed"),
    ("A1-01", "A1", "100% bonus depreciation (OBBBA 2025) drives cash taxes.", "Tested bonus OFF in break tests.",
     "Prob-weighted value moves < 1%; keep ON, verify with tax adviser.", "Documented"),
]
r = 5
for row_ in LOG:
    for j, v in enumerate(row_):
        c = wsL.cell(r, 1 + j, v); c.font = BOLD if j == 0 else BLACK; c.alignment = WRAP
    r += 1

# ======================= Sources
wsO = wb.create_sheet("Sources")
title(wsO, "DATA SOURCES", "Every hard-coded fact in Inputs / Capital_Structure / Market_Data traces to one of these.")
setw(wsO, {"A": 48, "B": 110})
SRC = [
    ("Q2-2026 Form 10-Q (balance sheet, debt note, shares, PP&E)", "https://www.sec.gov/Archives/edgar/data/1780312/000119312526342550/asts-20260630.htm"),
    ("Q2-2026 business update deck (8-K ex. 99.2)", "https://www.sec.gov/Archives/edgar/data/0001780312/000119312526342540/asts-ex99_2.htm"),
    ("2034 1.625% notes pricing (8-K ex. 99.1, Jul-2026)", "https://www.sec.gov/Archives/edgar/data/0001780312/000149315226033912/ex99-1.htm"),
    ("2034 notes closing / net proceeds", "https://www.businesswire.com/news/home/20260721294685/en/"),
    ("2036 2.25% notes pricing (8-K, Feb-2026)", "https://www.sec.gov/Archives/edgar/data/1780312/000149315226007126/ex99-1.htm"),
    ("2036 2.00% notes conversion price", "https://app.dealroom.co/news/feed/ast-spacemobile-prices-1b-convertible-notes-offering-up-from-850m"),
    ("2032 4.25% notes terms (8-K, Jan-2025)", "https://www.sec.gov/Archives/edgar/data/1780312/000149315225003793/ex99-1.htm"),
    ("FY2025 Form 10-K (Ligado commitments, launch commitments)", "https://www.sec.gov/Archives/edgar/data/1780312/000178031226000006/asts-20251231.htm"),
    ("Q1-2026 Form 10-Q (2020 Plan options)", "https://www.sec.gov/Archives/edgar/data/0001780312/000119312526216950/asts-20260331.htm"),
    ("Q2-2026 earnings call ($21-23mm/sat, 45-60 sats, guidance)", "https://www.fool.com/earnings/call-transcripts/2026/08/17/ast-spacemobile-asts-q2-2026-earnings-call-transcript/"),
    ("BlueBird Block 2 lifetime (secondary)", "https://space.skyrocket.de/doc_sdat/bluebird-2.htm"),
    ("Interactive Brokers API - weekly OHLCV ASTS (conid 480745767), SPY (756733)", "Retrieved via connected IBKR account, 10-Sep-2026"),
    ("10-year Treasury yield 4.84% (10-Sep-2026)", "https://tradingeconomics.com/united-states/government-bond-yield"),
    ("Damodaran implied ERP 4.42% (1-Jul-2026)", "https://aswathdamodaran.blogspot.com/2026/07/country-risk-drivers-measures-and.html"),
    ("Iridium FY2025 results (margin benchmark)", "https://investor.iridium.com/2026-02-12-Iridium-Announces-2025-Results-Issues-2026-Outlook"),
    ("T-Mobile T-Satellite pricing ($10/mo)", "https://www.t-mobile.com/coverage/satellite-phone-service"),
]
for j, (a_, b_) in enumerate(SRC):
    put(wsO, f"A{5+j}", a_); put(wsO, f"B{5+j}", b_, GREY)

# ======================= Notes
wsN = wb.create_sheet("Notes")
title(wsN, "METHODOLOGY, USAGE & LIMITATIONS", "")
setw(wsN, {"A": 150})
NOTES = [
    "HOW TO USE", "Edit blue cells on Inputs only (scenario columns D-G; globals in D). Everything else recalculates. Confirm Checks!C3 reads ALL PASS.",
    "Monte Carlo, tornado, 2-D grids and reverse DCF are stamped values from analytics.py; re-run after changing inputs.",
    "", "METHOD",
    "Unlevered DCF (FCFF) from 1-Jul-2026, valued at 10-Sep-2026, mid-period discounting with a period-specific WACC (growth phase fading 2031-35 to mature).",
    "Revenue: MNO wholesale revenue share = partner base x coverage(fleet) x logistic adoption x ASTS ARPU; plus government and gateway revenue.",
    "Constellation: fleet targets drive launches, cohort retirements after design life, launch losses, and CIP pre-funding credit.",
    "Tax: NOL pool with 80% cap; 100% bonus depreciation (switchable). Terminal: Gordon growth on normalised 2041 FCFF (steady-state replacement capex).",
    "Equity: EV + liquid assets - debt - converts at face, then an order-independent, value-consistent dilution engine converts instruments whose trigger < value.",
    "Four scenarios are all live; value is probability-weighted. Per-share values are floored at zero (limited liability).",
    "", "KEY LIMITATIONS (see Review_Log for full list)",
    "1. Forward drivers (adoption, ARPU, opex) are judgement - no one has observed mature D2D broadband economics. Tier-1 take rate dominates value.",
    "2. Fixed-plan DCF ignores management flexibility (abandonment/scale-back) - Distress/Bear values understate true option value of equity.",
    "3. Capital raises assumed at fair value; raising below intrinsic value would dilute further (see Risk funding gap).",
    "4. Ligado revenue-share %, possible Tax Receivable Agreement, and two stale award counts are unverified (Open items).",
    "5. Capex timed at launch (~-1.8% per-share impact if paid a year earlier). Block 1 satellites ignored for coverage (conservative).",
    "6. USD throughout. Not investment advice: this is an analytical model, and the author is not a financial adviser.",
]
for j, t in enumerate(NOTES):
    c = wsN.cell(4 + j, 1, t); c.font = BOLD if t.isupper() and t else BLACK; c.alignment = WRAP

# ======================= Dashboard
wsD = wb.create_sheet("Dashboard", 0)
title(wsD, "AST SPACEMOBILE (NASDAQ: ASTS) - INTRINSIC VALUATION MODEL",
      "Valuation date 10-Sep-2026. USD. Balance sheet 30-Jun-2026 pro forma Jul-2026 convertible. Live links unless marked 'stamped'.")
setw(wsD, {"A": 50, "B": 15, "C": 15, "D": 15, "E": 15, "F": 15, "G": 3, "H": 16})
r = 4
put(wsD, f"A{r}", "MODEL STATUS", BOLD); put(wsD, f"B{r}", f"={B.CHECK_STATUS}", BOLD); wsD[f"B{r}"].fill = FILL_Y; r += 2
section(wsD, r, "Headline", 6); r += 1
head = [("Current share price (IBKR)", f"={MS['price']}", "$"),
        ("Probability-weighted intrinsic value", f"=Valuation_Summary!F{VS['vps']}", "$"),
        ("Upside / (downside) vs price", f"=Valuation_Summary!F{VS['vps']}/{MS['price']}-1", "%"),
        ("Monte Carlo mean (stamped)", f"={MC['mean']}", "$"),
        ("Monte Carlo P10 - P90 (stamped)", f"=TEXT({MC['p10']},\"$0\")&\" - \"&TEXT({MC['p90']},\"$0\")", None),
        ("P(intrinsic value > price) (stamped)", f"={MC['pab']}", "%"),
        ("Model-implied expected return p.a., 3-yr (prob-weighted)", f"=Valuation_Summary!F{VS['er3']}", "%"),
        ("Model-implied expected return p.a., 3-yr (MC mean)", f"={MC['er3']}", "%"),
        ("Realised volatility (annualised)", f"={MS['vol']}", "%"),
        ("Growth-phase WACC / terminal WACC", f"=TEXT({WR['w_hi']},\"0.0%\")&\" / \"&TEXT({WR['w_t']},\"0.0%\")", None),
        ("Market-implied Base Tier-1 take rate (stamped reverse DCF)", A["rev"][0], "%")]
for lab, f, fmt in head:
    put(wsD, f"A{r}", lab); c = put(wsD, f"B{r}", f, GREEN if isinstance(f, str) else BLUE, fmt); r += 1
wsD["B8"].fill = FILL_Y
for rr_ in range(7, r):
    wsD[f"B{rr_}"].alignment = Alignment(horizontal="right")
r += 1; section(wsD, r, "Scenarios (live)", 6); r += 1
for j in range(4):
    put(wsD, f"{CL(2+j)}{r}", I.SCEN[j], BOLD); wsD[f"{CL(2+j)}{r}"].alignment = Alignment(horizontal="right")
put(wsD, f"F{r}", "Weighted", BOLD); wsD[f"F{r}"].alignment = Alignment(horizontal="right"); SC0 = r; r += 1
for lab, key, fmt in [("Probability", "prob", "%"), ("Value per share ($)", "vps", "$"), ("Enterprise value ($mm)", "ev", "$mm"),
                      ("Revenue 2030 ($mm)", "rev30", "$mm"), ("Revenue 2035 ($mm)", "rev35", "$mm"),
                      ("EBITDA margin 2040", "m40", "%"), ("Peak funding need ($mm)", "minfcf", "$mm")]:
    put(wsD, f"A{r}", lab)
    for j in range(5):
        col = CL(2 + j)
        if j == 4 and key not in ("prob", "vps"):
            continue
        put(wsD, f"{col}{r}", f"=Valuation_Summary!{col}{VS[key]}", GREEN, fmt)
    r += 1
r += 1; section(wsD, r, "For the portfolio analysis", 6); r += 1
for t in ["The earlier portfolio work used a 12% expected return for ASTS as an explicit placeholder guess.",
          "This model replaces it with the model-implied figures above: expected return and volatility for the ASTS sleeve.",
          "Interpretation: at today's price the market is paying roughly for Base-case execution; the payoff is highly skewed",
          "(meaningful probability of ~zero equity value, long right tail). Not investment advice."]:
    put(wsD, f"A{r}", t, GREY); r += 1
# charts
ch = BarChart(); ch.type = "col"; ch.title = "Value per share by scenario ($)"; ch.style = 10
ch.add_data(Reference(wsD, min_col=2, max_col=5, min_row=SC0 + 2, max_row=SC0 + 2), from_rows=True, titles_from_data=False)
ch.set_categories(Reference(wsD, min_col=2, max_col=5, min_row=SC0, max_row=SC0)); ch.legend = None; ch.height = 7; ch.width = 13
ch.series[0].tx = SeriesLabel(v="$/share")
wsD.add_chart(ch, "H4")
cb = wb["Calc_Base"]; RB = B.CALC_ROWS[2]
lc = LineChart(); lc.title = "Base case: revenue, EBITDA, FCFF ($mm)"; lc.style = 12; lc.height = 7; lc.width = 13
for key in ("rev", "ebitda", "fcf"):
    ref = Reference(cb, min_col=4, max_col=18, min_row=RB[key], max_row=RB[key])
    lc.add_data(ref, from_rows=True, titles_from_data=False)
lc.series[0].tx = SeriesLabel(v="Revenue"); lc.series[1].tx = SeriesLabel(v="EBITDA"); lc.series[2].tx = SeriesLabel(v="FCFF")
lc.set_categories(Reference(cb, min_col=4, max_col=18, min_row=RB["period"], max_row=RB["period"]))
lc.x_axis.tickLblPos = "low"
wsD.add_chart(lc, "H20")

# ======================= sheet order
order = ["Dashboard", "Valuation_Summary", "Inputs", "Capital_Structure", "WACC", "Market_Data", "Calc_Base", "Calc_Bear",
         "Calc_Bull", "Calc_Distress", "Sensitivity", "Monte_Carlo", "Risk", "Checks", "Review_Log", "Sources", "Notes"]
wb._sheets = [wb[n] for n in order]
wb.active = 0
for ws in wb.worksheets:
    ws.sheet_properties.tabColor = {"Dashboard": "1F3864", "Inputs": "FFC000", "Checks": "00B050", "Review_Log": "7030A0"}.get(ws.title)
out = "/home/claude/asts/ASTS_Valuation_Model.xlsx"
wb.save(out); print("saved", out)
